### ISSUE TITLE
Showcase Link 404

### ISSUE THREAD

**Issue by agerlach** [SciML/sciml.ai#102]
When visiting https://sciml.ai/showcase/

<img width="849" alt="image" src="https://user-images.githubusercontent.com/599421/218803066-4f85dda8-3cdb-4b3c-9a0d-ed4331a65d88.png">

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/sciml.ai/commit/d0c64590b8c788d39a1092a4bb80fc9b243658d1 my guess is that this fixes it.

**Comment by agerlach** [comment]
Yep, working now
