### ISSUE TITLE
Broken (404) links on main page "Physics Informed Model Discovery"

### ISSUE THREAD

**Issue by DrEntropy** [SciML/sciml.ai#105]
Two links on the front page  (https://sciml.ai/#:~:text=Physics%2DInformed%20Model%20Discovery)  are broken. 
I don't know where they were supposed to go:
https://diffeq.sciml.ai/latest/analysis/parameter_estimation/
https://diffeq.sciml.ai/latest/analysis/parameter_estimation/#Bayesian-Methods-1

The closest relevant page Icould find was this : 
https://docs.sciml.ai/Overview/stable/highlevels/inverse_problems/
I am not confident that this was the intent though.

**Comment by ChrisRackauckas** [comment]
I pushed some link fixes which should handle this.
