### ISSUE TITLE
NumFOCUS: GSoC 2024 Update

### ISSUE THREAD

**Issue by henrykironde** [SciML/sciml.ai#107]
If you intend to participate, kindly ensure you update the information as there are only a few hours left until the deadline.

ref: 
https://github.com/numfocus/gsoc
https://github.com/numfocus/gsoc/blob/master/2024/ideas-list.md

**Comment by ChrisRackauckas** [comment]
Thank you. I opened a PR. Please in the future if we could receive notice more than a few hours before it's due that would be helpful.

**Comment by henrykironde** [comment]
Sorry about that, please ensure that you are subscribed to the affiliated mailing list and google mentors' numfocus group.

**Comment by ChrisRackauckas** [comment]
Can you double check I'm still on it?
