### ISSUE TITLE
Add a footer?

### ISSUE THREAD

**Issue by tlienart** [SciML/sciml.ai#45]
There's currently no footer in your layout e.g. on the front page:

![Screenshot 2020-07-17 at 11 53 41](https://user-images.githubusercontent.com/10897531/87773972-301ff500-c824-11ea-8d0a-fd0e36554e92.png)

even if you decide to leave it blank you might want to

1. add a hrule there to indicate end of page
2. add some space

possibly if you were to add one you might want to add a contact section or something like it

Ps: you might want one that matches https://benchmarks.sciml.ai/

**Comment by ChrisRackauckas** [comment]
Is there a way to enable some powered by Franklin.jl and the Julia Programming Language kind of thing?

**Comment by tlienart** [comment]
yes you would just need to put that in https://github.com/SciML/sciml.ai/blob/master/_layout/page_foot.html

**Comment by tlienart** [comment]
I'll open a PR

**Comment by tlienart** [comment]
#48
