### ISSUE TITLE
Add topics to the repo

### ISSUE THREAD

**Issue by tlienart** [SciML/sciml.ai#46]
For discoverability, it could be good to add topics to this repo?

Also it would be great if you added `#franklin` as it helps users who want to see example websites :) thanks!

**Comment by ChrisRackauckas** [comment]
Where do the topics go?

**Comment by tlienart** [comment]
![Screenshot 2020-07-17 at 14 01 23](https://user-images.githubusercontent.com/10897531/87784155-0e2f6e00-c836-11ea-83a3-e943cbe28f2b.png)

I just added "machine-learning" and "differential-equations" which I'm assuming are non-controversial
