### ISSUE TITLE
Modern look to the SciML website

### ISSUE THREAD

**Issue by RohitRathore1** [SciML/sciml.ai#59]
@ChrisRackauckas As our current website has been developed using the Jekyll theme. So to get a modern look I will use React and GraphQL. Before making the changes I am working on the design. If this sounds good then tell me :)

**Comment by ChrisRackauckas** [comment]
I don't care about the libraries so much. It's really the look. I'd say https://fenicsproject.org/ looks nice, or https://julialang.org/ . The main thing would probably be the banner on the top. I think @cormullion may have made it? That would be the starting place. It should end up as a Franklin template though, and it would be good to share design ideas before putting the work in to make the template.

Pulling @tlienart as the Franklin dev, @ViralBShah for opinions, etc.

**Comment by cormullion** [comment]
Yes, I did make some images last year -  

<img width="620" alt="Screenshot 2021-03-03 at 12 02 50" src="https://user-images.githubusercontent.com/52289/109802992-6a55cf80-7c18-11eb-8b25-273b372c33c8.png">

but they weren't used. Too "old school" I expect. (And that font wasn't too popular either.) 😅😂🤣

**Comment by ChrisRackauckas** [comment]
I like that black background design other than the logo looking a little too "plastic".

That design on the bottom is actually quite nice! If the banner on the top was instead with Black test and the logo colors I think it's good? Maybe making those ribbons black in the background. But that general idea works IMO, making maybe the top background a bit transparent black to make the sidebars part be behind it?

**Comment by cormullion** [comment]
Trouble is, I don't like/do web design, so ideas have to be re-organized/re-factored to suit the responsive CSS stuff.

**Comment by ChrisRackauckas** [comment]
That's fine. I think if someone comes up with the look, someone else can figure out how to code it up. Getting a design is the hard part!

**Comment by TeAmP0is0N** [comment]
ig we can put any of the above logos when we will build the navbar and there will be other tabs in the Navbar. These tabs can have some drop-down tabs like if I talk about our most popular projects tabs then it will be something like this:
Projects  
     |
     |- our popular projects
and whenever a person will point their pointer in these tabs then it will directly hover them in that project and can redirect the projects section in a new section or we can show after completing the banner part.
Or, just have a look at this website as well: https://www.codeuino.org/

**Comment by TeAmP0is0N** [comment]
Or I am not able to frame in words. We can do one thing I will prepare a simple site then according to your opinions I can make changes?

**Comment by cormullion** [comment]
If I recall, the problem with the previous styling attempt was that it didn't work well on both desktop and mobile, so getting that right would be a good foundation!

**Comment by tlienart** [comment]
I might be missing some context but my suggestions would be:

1. Someone to put up a framework based skeleton (eg bootstrap or whatever, simple is better to help long term maintenance)
1. I help out porting that to Franklin (you could drop Franklin but I objectively think it makes maintenance by non web people relatively easier than the likes of Jekyll or other fancy JS stuff like react etc 

Both Julicon and Julialang website are basically Franklin + bootstrap layout.

IMO whatever is chosen should take into account who maintains / add content in the long run and how much work it would be to get a new person to do that :)

**Comment by TeAmP0is0N** [comment]
@tlienart Yeah, I agree with both points.. I am available to contribute for a long time.. And, I guess it won't be too much difficult to add a new content

**Comment by ViralBShah** [comment]
@ChrisRackauckas ok to close?
