### ISSUE TITLE
Older post titles missing on /news page

### ISSUE THREAD

**Issue by lorenzoh** [SciML/sciml.ai#69]
On  [sciml.ai/news](sciml.ai/news), posts from before 2020 show "nothing" as a title. 

<img width="586" alt="grafik" src="https://user-images.githubusercontent.com/28812146/138281750-eac79b94-9d6e-4b65-8b75-88a2f49c8bd3.png">

**Comment by ChrisRackauckas** [comment]
@tlienart could we get help with this?
