### ISSUE TITLE
Benchmarks link leads to LinearSolve.jl website?

### ISSUE THREAD

**Issue by ranocha** [SciML/sciml.ai#85]
https://benchmarks.sciml.ai/dev/ linked from "Benchmarks" at https://sciml.ai/ is 

![image](https://user-images.githubusercontent.com/12693098/178288766-96306ddb-42e0-42e3-9206-cf269d1026ae.png)

That's not intended, is it?

**Comment by ChrisRackauckas** [comment]
Fixed. Now look at the site 😉
